### PR TITLE
Move to common test

### LINKED ISSUE #57: move to common test

### PR DESCRIPTION
**Pull request by kjnilsson**
Fixes #57

### CODE REVIEW

**Comment by michaelklishin** [comment]
This executes all tests on a single node while the original version uses 2 nodes.

**Comment by kjnilsson** [comment]
The original uses a separate node for the `restart_node` test. I assumed that was for technical rather than functional reasons as I think it is just testing that delayed messages survive a node restart which can be tested equally well using the default node with our testing helpers. Unless I am missing something which I may well be. :)

**Comment by michaelklishin** [comment]
Yes, looks like you are right. A single node may be even more descriptive then.

**Comment by michaelklishin** [comment]
@kjnilsson there is one test in master that doesn't exist in stable, please merge and resolve conflicts.

**Pull request merged**
